on: [push]
jobs:
  build-and static-analysis:
    runs-on: ubuntu-latest
    container:
      image: gcc-arm-none-eabi-10.3-2021.10:latest
    steps:
      - name: Check the ropsitory
        uses: actions/checkout@v3
      - run: make
      - run: make cppcheck