FROM ubuntu:22.04

# Install necessary packages
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update \
    && apt-get install -y wget bzip2make unzip cppcheck
#Create a non-root user named "ubuntu"
# But put in root group since GITHUB actions needs permissions
# to create tmp files.
RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo \
    -u 1001 ubuntu
WORKDIR /home/ubuntu