on: [push]

jobs:
  build-and-static-analysis:
    runs-on: ubuntu-latest
    container:
      image: ahmedkh11/gcc-arm:latest
    steps:
      - name: Check the ropsitory
        uses: actions/checkout@v4
      - run: make
      - run: make cppcheck